# Generated by Django 5.0 on 2024-02-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('content', models.TextField(verbose_name='контент')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_student.section')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='вопрос')),
                ('correct_answer', models.CharField(max_length=255, verbose_name='правильный оответ')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_student.material', verbose_name='материал')),
            ],
        ),
    ]
