# Generated by Django 5.0 on 2024-02-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'материал', 'verbose_name_plural': 'материалы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'тест', 'verbose_name_plural': 'тесты'},
        ),
        migrations.AlterField(
            model_name='material',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_student.section', verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название секции'),
        ),
    ]
