# Generated by Django 5.0 on 2024-02-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_student', '0002_alter_material_options_alter_test_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание секции'),
        ),
    ]
