# Generated by Django 5.0 on 2024-02-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_student', '0003_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое содержание'),
        ),
    ]
