# Generated by Django 5.0 on 2024-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_student', '0005_test_option1_test_option2_test_option3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='correct_answer',
            field=models.CharField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3')], max_length=255, verbose_name='правильный оответ'),
        ),
    ]
